amélioration de l'amélioration
entrepreneur-interet-general/manifeste-eig pull request #10
Opened 2018-10-11 15:10 UTC by phileas-condemine

version littéraire des 3 exemples. Diagnostic dans un tableau. La proposition pour l'avenir est un peu trop vague et pipot et devrait être plus percutante et précise.

2018-10-12 15:16 UTC, vict0rsch requested changes

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +| Dette technique | Un risque apparaît en cas de départ de toutes les personnes compétentes, sinon un produit documenté et dont le code source est disponible permettent une réappropriation de l'outil
Je suis pas convaincu par l'utilisation d'un tableau qui jure avec les autres pages et rend l'approche très froide et analytique. 

Je pense qu'il faut formuler une phrase d'intro qui résume l'enjeu (amélioration vs remplacement) et présente les 3 cas d'usage de ce nouveau paradigme. Par la suite, 3 petits paragraphes présentent le contraste amélioration/remplacement pour cycle de vie / coût / dette 

Formuler des phrases permet aussi de ne pas tomber dans des résumés sombres comme `qqETP, UX/UI remontés par les utilisateurs` (même si on voit où tu veux en venir)

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +Nous recommandons une approche itérative et continue visant à délivrer une première version minimale du produit rapidement MAIS avec une vision ie en s'appuyant d'emblée sur la technologie pertinente
Pas de full upper case :p

`MAIS avec une vision ie [...]` -> `mais avec une vision claire: il faut choisir d'emblée la technologie pertinente pour les ambitions du produit`

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +sur un framework web commercial Beyond20/20. Par conséquent il est impossible de le faire
Pas la peine de tout nommer:  `solution web` sans `HTML4`, `framework web commercial` sans `Beyond20/20`, `l'entreprise` sans  `Beyond2020 `

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +Présent : Aujourd'hui la DREES souhaite utiliser une autre solution pour exposer ces données afin de pouvoir intégrer des points API et un meilleur référencement sur les moteurs de recherche. [Techni
A contrario, la DREES souhaite aujourd'hui utiliser [...]

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +Présent : Aujourd'hui la DREES souhaite utiliser une autre solution pour exposer ces données afin de pouvoir intégrer des points API et un meilleur référencement sur les moteurs de recherche. [Techni
Je vois pas bien l'apport pour le lecteur de la partie `[Technique]`

2018-10-12 15:16 UTC, Vict0rSch commented on sources/ameliorer.org
> +- Si j'utilise une solution open source et que je suis séduit par les fonctionnalités d'une autre solution. Je peux intégrer ces méthodes et idées, il n'est pas nécessaire de changer de solution ie r
`Exemples` trop techy je pense, pas la peine

2018-10-15 10:37 UTC, bzg requested changes
OK avec les propositions de @Vict0rSch

2018-10-15 10:37 UTC, bzg commented on sources/ameliorer.org
> +sur un framework web commercial Beyond20/20. Par conséquent il est impossible de le faire
Je ne citerais pas le nom du framework commercial.

2018-10-15 10:37 UTC, bzg commented on sources/ameliorer.org
> +Présent : Aujourd'hui la DREES souhaite utiliser une autre solution pour exposer ces données afin de pouvoir intégrer des points API et un meilleur référencement sur les moteurs de recherche. [Techni
"intégrer des points d'API" => "exposer ses données de façon structurée" ?

Pour déjargonner un peu.

2018-10-15 10:37 UTC, bzg commented on sources/ameliorer.org
> +Dans la branche spécifique de la tarificaton en assurance, on calibre des modèles linéaires généralisés afin d'ajuster la prime aux risques. Pour cela, certains assureurs utilisent des outils commerc
> qui ne savent plus coder

BIM! Trop général à mon avis.

> commercial ou opensource

`commercial` et `opensource` ne sont pas antithétiques - mieux vaut dire `fermé ou open source` (il y a du commercial (fermé) gratuit, de l'open source gratuit, du commercial payant, de l'open source payant, etc.: c'est compliqué.)

2018-10-15 10:38 UTC, bzg commented
Du coup @phileas-condemine tu nous dis si tu as un moment pour faire ces modifications (dans un commit sur la même branche que tu pousses) ou si tu veux qu'on prenne le relais (en mergeant ta proposition et en l'améliorant à partir du merge) ?

2018-10-15 13:31 UTC, phileas-condemine commented
Commercial, je voulais dire propriétaire, fermé c'est bien.
Je peux vous laisser gérer svp ? Je suis en congés là et c'est un peu
galère la connexion à internet.
Promis je vous rejoins la semaine pro

On Mon, Oct 15, 2018 at 12:38 PM Bastien <notifications@github.com> wrote:

> Du coup @phileas-condemine <https://github.com/phileas-condemine> tu nous
> dis si tu as un moment pour faire ces modifications (dans un commit sur la
> même branche que tu pousses) ou si tu veux qu'on prenne le relais (en
> mergeant ta proposition et en l'améliorant à partir du merge) ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/entrepreneur-interet-general/manifeste-eig/pull/10#issuecomment-429797838>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXFZXvJ7FdYdEBmW--CxASC4dzoaax-jks5ulGWigaJpZM4XXwp1>
> .
>

2018-10-15 14:22 UTC, bzg commented
Ok @phileas-condemine, pas de souci pour prendre le relais !

2018-10-16 15:53 UTC, merged

2018-10-16 15:59 UTC, bzg commented
J'ai mergé et fait quelques modifications qui correspondent à celles faites dans cette PR.