Update emmanuel
entrepreneur-interet-general/manifeste-eig pull request #8
Opened 2018-10-11 14:57 UTC by emmanuelgautier1994

2018-10-11 15:07 UTC, AntoineAugusti commented on sources/composer.org
> +Imaginez un instant qu'en marchant dans la rue avec un.e ami.e, vous
Il y a un débat à avoir sur l'écriture inclusive. Je suis contre pour un tel document. À débattre.

2018-10-11 15:07 UTC, AntoineAugusti commented on sources/composer.org
> +tombez dans une faille spatio-temporelle, et vous retrouvez
Au-delà du fait que j'adore ta façon de rédiger et plus particulièrement ton histoire, je pense que ça va être difficile de faire ça dans ce document car ceci contraste fortement avec la rédaction des autres principes et que la place est limitée.

Je pense que tu peux romancer mais étant beaucoup plus succinct, en se focalisant sur les 2 premiers paragraphes.

2018-10-12 07:05 UTC, bzg commented on sources/composer.org
> +Imaginez un instant qu'en marchant dans la rue avec un.e ami.e, vous
Je suis pour la double flexion ("elles et ils", "celles et ceux", etc.) plutôt que le point médian.

2018-10-12 15:03 UTC, vict0rsch requested changes

2018-10-12 15:03 UTC, Vict0rSch commented on sources/composer.org
> +tombez dans une faille spatio-temporelle, et vous retrouvez
Je suis d'accord. C'est sympa entre nous mais ça altère un peu le message ; faut pas passer pour de doux-dingues qui rêvent d'un monde chelou.

Je pense qu'au delà de la longueur de la métaphore il faut la rendre légèrement plus sobre. 

Aussi attention à la métaphore du passé et des hommes préhistoriques: il faut pas que ce soit interprété comme les eig viennent du futur éduquer ces pauvres arriérés préhistoriques des administrations parce que c'est pas du tout le message :p

2018-10-15 10:40 UTC, bzg requested changes
@emmanuelgautier1994 OK pour ces évolutions ? Est-ce que tu veux les prendre ou nous les laisser ?

2018-10-15 10:40 UTC, bzg commented on sources/composer.org
> +tombez dans une faille spatio-temporelle, et vous retrouvez
D'accord avec Antoine. Par contre, la fluidité imagée de ton style pourrait dynamiser l'introduction et la conclusion, et vivifier le blog qui annoncera le manifeste !

2018-10-15 10:40 UTC, bzg commented on sources/composer.org
> +tombez dans une faille spatio-temporelle, et vous retrouvez
C'est aussi qu'on prend trop de temps à présenter une idée qui est devenue un lieu commun, le fait de ne pas réinventer la roue. Je sais que le dicton est toujours d'actualité, mais je pense que l'enjeu est moins de le rendre popultaire (personne ne propose de réinventer la roue) que de préciser ce que ça veut dire pour un projet informatique d'une administration: utiliser les normes et standards existants, interfacer, etc.

2018-10-16 15:49 UTC, merged

2018-10-16 15:52 UTC, bzg commented on sources/composer.org
> +tombez dans une faille spatio-temporelle, et vous retrouvez
J'ai mergé en mettant en commentaire la partie très imagée du début - on la garde sous la main pour s'inspirer et en garder le rythme de lecture.